Weichat interface
S2U2MLancer/mindfly pull request #13
Opened 2018-07-02 05:42 UTC by mypennyXue

#12 微信接口定义

2018-07-03 14:41 UTC, xiayy860612 requested changes

2018-07-03 14:41 UTC, xiayy860612 commented on server/slancer-mindfly-service-account/src/main/java/slancer/mindfly/service/account/AccountServiceApp.java
> +	public static void main(String[] args) throws Exception {
因为codestyle的问题引起的修改全部回滚, 目前看到的格式不太对劲.

最好把你当前的分支基于dev做rebase, 或者是重新从dev切出来后做cherrypick

2018-07-03 14:42 UTC, xiayy860612 commented on server/slancer-mindfly-service-account/src/main/java/slancer/mindfly/service/account/AccountServiceApp.java
> +	public static void main(String[] args) throws Exception {
你这里的提交太多了, 照理应该就只有一个提交, 关于接口设计的, 当然可能还有其他的实现

2018-07-04 01:08 UTC, mypennyXue commented on server/slancer-mindfly-service-account/src/main/java/slancer/mindfly/service/account/AccountServiceApp.java
> +	public static void main(String[] args) throws Exception {
好的 我改下

2018-07-06 13:53 UTC, xiayy860612 commented
ref https://developers.weixin.qq.com/miniprogram/dev/api/api-login.html

2018-07-06 13:53 UTC, closed without merging