We chat interface
S2U2MLancer/mindfly pull request #23
Opened 2018-07-09 14:29 UTC by mypennyXue

define weChat interface

2018-07-11 12:04 UTC, xiayy860612 requested changes

2018-07-11 12:04 UTC, xiayy860612 commented on server/slancer-mindfly-service-account/src/main/java/slancer/mindfly/service/account/controller/user/dto/WeChatResponseDTO.java
> +public class WeChatResponseDTO {
这个response不仅仅用于微信，不管用户以何种方式登陆， 只要成功都会返回。
需要重新命名下

2018-07-11 12:04 UTC, xiayy860612 commented on server/slancer-mindfly-service-account/src/main/java/slancer/mindfly/service/account/service/account/WeChatService.java
> +public class WeChatService {
Service设计请遵循我们之前的设计接口

2018-07-11 12:06 UTC, xiayy860612 requested changes

2018-07-11 12:06 UTC, xiayy860612 commented on server/pom.xml
> +
这个可以放到项目根目录下的POM里

2018-07-11 12:06 UTC, xiayy860612 commented on server/slancer-mindfly-core/src/main/java/slancer/mindfly/core/enumhandler/IntEnumParser.java
> +     * @return   ''
请添加下文字说明

2018-07-15 14:42 UTC, mypennyXue commented on server/pom.xml
> +
这个是在 根目录下边

2018-07-16 14:02 UTC, xiayy860612 requested changes

2018-07-16 14:02 UTC, xiayy860612 commented on server/slancer-mindfly-service-account/src/main/java/slancer/mindfly/service/account/controller/user/dto/WeChatRegistDTO.java
> +	private String password;
微信注册不需要密码, 此时的密码可以用随机值;
但如果之后支持手机注册, 则密码会在注册时提供;
所以要考虑密码生成的地方.

2018-07-16 14:02 UTC, xiayy860612 commented on server/slancer-mindfly-service-account/src/main/java/slancer/mindfly/service/account/service/account/bo/UserEntityToken.java
> +public class UserEntityToken {
token这块的功能已经有了的, 之前在实现token部分已经做了.
你可以看下

2018-07-17 13:33 UTC, xiayy860612 requested changes

2018-07-17 13:33 UTC, xiayy860612 commented on server/slancer-mindfly-service-account/src/main/java/slancer/mindfly/service/account/service/account/bo/BindWeChatBO.java
> +    private String code;
思考下, 用户在绑定新登陆方式时, 真正需要的 有些什么数据

2018-07-17 14:48 UTC, xiayy860612 approved these changes

2018-07-22 06:02 UTC, merged