define database
S2U2MLancer/mindfly pull request #24
Opened 2018-07-09 15:01 UTC by mypennyXue

define wechat database

2018-07-10 12:01 UTC, xiayy860612 requested changes

2018-07-10 12:01 UTC, xiayy860612 commented on server/slancer-mindfly-service-account/src/main/resources/db/migration/V2__wechat_info.sql
> +CREATE TABLE IF NOT EXISTS `user_info` (
user_info表已经存在， 只用于用户， 不用于账户。
请看下之前的设计

2018-07-10 13:41 UTC, mypennyXue commented
eoor

2018-07-10 13:47 UTC, mypennyXue commented
define wechat database

2018-07-10 13:48 UTC, mypennyXue commented
fix test

2018-07-11 12:02 UTC, xiayy860612 requested changes

2018-07-11 12:02 UTC, xiayy860612 commented on server/slancer-mindfly-service-account/src/test/resources/db/migration/V2__wechat_info.sql
> +CREATE TABLE IF NOT EXISTS `wechat_info` (
wechat_info改为wechat_account, 尽量我们命名的时候能表达一定的含义

2018-07-11 12:02 UTC, xiayy860612 commented on server/slancer-mindfly-service-account/src/test/resources/db/migration/V2__wechat_info.sql
> +  `user_id` bigint(20)  NOT NULL,
user_id的类型错误, 需要和主键的表的类型一致;
open_id的类型请参见文档

2018-07-12 13:00 UTC, mypennyXue commented on server/slancer-mindfly-service-account/src/test/resources/db/migration/V2__wechat_info.sql
> +  `user_id` bigint(20)  NOT NULL,
好的

2018-07-12 13:58 UTC, closed without merging